  version: "3"
  services:


    mongo:
      image: 'mongo'
      environment:
        - MONGO_INITDB_DATABASE=test
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      ports:
        - 27017:27017
      volumes:
      - /home./:/data/db


