spring:
  application:
    name: Project
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
      username: your_username
      password: your_password



server:
  port: 9090

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: ==================================================AnsySan==================================================

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33